import { requireUser } from '../shared/auth.js';
import { applyCors, methodNotAllowed, sendJson } from '../shared/http.js';
import { checkRateLimit } from '../shared/rateLimit.js';

const MAX_TEXT = 8000;
const GEMINI_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent';

export default async function handler(req, res) {
  if (applyCors(req, res)) return;
  if (req.method !== 'POST') return methodNotAllowed(res, ['POST']);

  const auth = await requireUser(req);
  if (!auth.ok) return sendJson(res, auth.status, { ok: false, error: auth.error });

  const rate = checkRateLimit(`ai-check:${auth.user.id}`, { limit: 10, windowMs: 60_000 });
  if (!rate.allowed) {
    return sendJson(res, 429, { ok: false, error: { message: 'Too many requests. Try again shortly.' } });
  }

  const text = String(req.body?.text || '').trim();
  if (!text) return sendJson(res, 400, { ok: false, error: { message: 'Text is required.' } });
  if (text.length > MAX_TEXT) {
    return sendJson(res, 400, { ok: false, error: { message: `Text must be under ${MAX_TEXT} characters.` } });
  }
  if (!process.env.GEMINI_API_KEY) {
    return sendJson(res, 503, { ok: false, error: { message: 'AI service not configured.' } });
  }

  const prompt = `You are an expert AI content detector. Analyze the text below and determine how likely it was generated by an AI system (GPT, Gemini, Claude, etc.) vs written by a human.

Return ONLY a valid JSON object with this exact structure (no markdown, no extra text):
{
  "probability": <integer 0-100>,
  "verdict": "<one of: Almost Certainly Human | Likely Human | Uncertain | Likely AI | Almost Certainly AI>",
  "confidence": "<one of: Low | Medium | High>",
  "indicators": ["<indicator1>", "<indicator2>", "<indicator3>"],
  "explanation": "<2-3 sentence explanation>"
}

TEXT TO ANALYZE:
"""
${text}
"""`;

  try {
    const r = await fetch(`${GEMINI_URL}?key=${process.env.GEMINI_API_KEY}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ role: 'user', parts: [{ text: prompt }] }],
        generationConfig: { temperature: 0.1, topP: 0.9, maxOutputTokens: 512 }
      })
    });

    if (!r.ok) {
      const err = await r.json().catch(() => ({}));
      throw new Error(err?.error?.message || 'Gemini request failed.');
    }

    const payload = await r.json();
    const raw = payload?.candidates?.[0]?.content?.parts?.[0]?.text || '';
    const cleaned = raw.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
    let result;
    try { result = JSON.parse(cleaned); } catch {
      throw new Error('AI returned an unparseable response. Please try again.');
    }

    return sendJson(res, 200, { ok: true, result });
  } catch (e) {
    return sendJson(res, 500, { ok: false, error: { message: e.message || 'AI check failed.' } });
  }
}
