import { requireUser } from '../shared/auth.js';
import { applyCors, methodNotAllowed, sendJson } from '../shared/http.js';
import { checkRateLimit } from '../shared/rateLimit.js';

const MAX_CHECK    = 8000;
const MAX_REPHRASE = 6000;

/* ── Provider config ─────────────────────────────────────────────── */
const GROQ_URL      = 'https://api.groq.com/openai/v1/chat/completions';
const GROQ_MODEL    = 'llama-3.3-70b-versatile';

const GEMINI_URL    = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent';

const OR_URL        = 'https://openrouter.ai/api/v1/chat/completions';
const OR_MODEL      = 'meta-llama/llama-3.1-70b-instruct:free';

/* ── Tone system prompts ─────────────────────────────────────────── */
const MODE_PROMPTS = {
  professional: 'Rephrase the following text in a clear, professional, and business-appropriate tone. Keep it concise and impactful.',
  academic:     'Rephrase the following text in a formal academic tone suitable for research papers or reports. Use precise language and structured sentences.',
  simplified:   'Rephrase the following text in simple, easy-to-understand language. Use short sentences and avoid jargon so anyone can understand it.',
  creative:     'Rephrase the following text in an engaging, creative, and vivid tone. Make it expressive and memorable while preserving the core meaning.',
  formal:       'Rephrase the following text in a formal, polite, and respectful tone suitable for official communications and letters.'
};

/* ── AI-checker prompt ───────────────────────────────────────────── */
const CHECK_SYSTEM = `You are an expert AI content detector. Analyze the user's text and determine how likely it was generated by an AI system (GPT, Gemini, Claude, etc.) vs written by a human.
Respond with ONLY valid JSON (no markdown, no extra text):
{"probability":<0-100>,"verdict":"<Almost Certainly Human|Likely Human|Uncertain|Likely AI|Almost Certainly AI>","confidence":"<Low|Medium|High>","indicators":["<point1>","<point2>","<point3>"],"explanation":"<2-3 sentences>"}`;

/* ════════════════════════════════════════════════════════════════════
   MAIN HANDLER
════════════════════════════════════════════════════════════════════ */
export default async function handler(req, res) {
  if (applyCors(req, res)) return;
  if (req.method !== 'POST') return methodNotAllowed(res, ['POST']);

  const auth = await requireUser(req);
  if (!auth.ok) return sendJson(res, auth.status, { ok: false, error: auth.error });

  const body   = req.body || {};
  const action = String(body.action || '');
  const text   = String(body.text  || '').trim();

  if (!text) return sendJson(res, 400, { ok: false, error: { message: 'Text is required.' } });

  /* ── AI CHECKER ─────────────────────────────────────────────── */
  if (action === 'ai-check') {
    const rate = checkRateLimit(`ai-check:${auth.user.id}`, { limit: 10, windowMs: 60_000 });
    if (!rate.allowed) return sendJson(res, 429, { ok: false, error: { message: 'Too many requests. Try again shortly.' } });
    if (text.length > MAX_CHECK) return sendJson(res, 400, { ok: false, error: { message: `Text must be under ${MAX_CHECK} characters.` } });

    try {
      const raw = await withFallback([
        // 1. Groq — JSON mode, most reliable
        () => process.env.GROQ_API_KEY
          ? groqChat(CHECK_SYSTEM, `Analyze this text:\n"""\n${text}\n"""`, { jsonMode: true })
          : Promise.reject(new Error('no key')),

        // 2. Gemini — strip thinking blocks, regex JSON extraction
        () => process.env.GEMINI_API_KEY
          ? gemini(`${CHECK_SYSTEM}\n\nTEXT TO ANALYZE:\n"""\n${text}\n"""`, { temperature: 0.1 })
          : Promise.reject(new Error('no key')),

        // 3. OpenRouter — free Llama fallback
        () => process.env.OPENROUTER_API_KEY
          ? openRouter(CHECK_SYSTEM, `Analyze this text:\n"""\n${text}\n"""`)
          : Promise.reject(new Error('no key'))
      ]);

      const parsed = extractJson(raw);
      if (!parsed) throw new Error('AI returned an unparseable response. Please try again.');
      return sendJson(res, 200, { ok: true, result: parsed });
    } catch (e) {
      return sendJson(res, 500, { ok: false, error: { message: e.message || 'AI check failed.' } });
    }
  }

  /* ── REPHRASER ──────────────────────────────────────────────── */
  if (action === 'rephrase') {
    const rate = checkRateLimit(`rephrase:${auth.user.id}`, { limit: 20, windowMs: 60_000 });
    if (!rate.allowed) return sendJson(res, 429, { ok: false, error: { message: 'Too many requests. Try again shortly.' } });
    if (text.length > MAX_REPHRASE) return sendJson(res, 400, { ok: false, error: { message: `Text must be under ${MAX_REPHRASE} characters.` } });

    const mode        = String(body.mode || 'professional').toLowerCase();
    const systemMsg   = (MODE_PROMPTS[mode] || MODE_PROMPTS.professional) +
                        '\n\nReturn ONLY the rephrased text. No preamble, no explanation, no labels.';

    try {
      const rephrased = (await withFallback([
        // 1. Groq — Llama 3.3 70B, best quality
        () => process.env.GROQ_API_KEY
          ? groqChat(systemMsg, text)
          : Promise.reject(new Error('no key')),

        // 2. Gemini free
        () => process.env.GEMINI_API_KEY
          ? gemini(`${systemMsg}\n\nORIGINAL TEXT:\n"""\n${text}\n"""`, { temperature: 0.7, maxOutputTokens: 2048 })
          : Promise.reject(new Error('no key')),

        // 3. OpenRouter free
        () => process.env.OPENROUTER_API_KEY
          ? openRouter(systemMsg, text)
          : Promise.reject(new Error('no key'))
      ])).trim();

      if (!rephrased) throw new Error('AI returned an empty response. Please try again.');
      return sendJson(res, 200, { ok: true, rephrased, mode });
    } catch (e) {
      return sendJson(res, 500, { ok: false, error: { message: e.message || 'Rephrase failed.' } });
    }
  }

  return sendJson(res, 400, { ok: false, error: { message: 'Unknown action. Use "ai-check" or "rephrase".' } });
}

/* ════════════════════════════════════════════════════════════════════
   PROVIDER FUNCTIONS
════════════════════════════════════════════════════════════════════ */

async function groqChat(system, user, { jsonMode = false, temperature = 0.7 } = {}) {
  const body = {
    model:       GROQ_MODEL,
    messages:    [{ role: 'system', content: system }, { role: 'user', content: user }],
    temperature,
    max_tokens:  2048,
    top_p:       0.9
  };
  if (jsonMode) body.response_format = { type: 'json_object' };

  const r = await fetch(GROQ_URL, {
    method:  'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${process.env.GROQ_API_KEY}` },
    body:    JSON.stringify(body)
  });
  if (!r.ok) {
    const err = await r.json().catch(() => ({}));
    throw new Error(err?.error?.message || `Groq error (${r.status})`);
  }
  const payload = await r.json();
  return payload?.choices?.[0]?.message?.content || '';
}

async function gemini(prompt, { temperature = 0.2, maxOutputTokens = 1024 } = {}) {
  const r = await fetch(`${GEMINI_URL}?key=${process.env.GEMINI_API_KEY}`, {
    method:  'POST',
    headers: { 'Content-Type': 'application/json' },
    body:    JSON.stringify({
      contents:         [{ role: 'user', parts: [{ text: prompt }] }],
      generationConfig: { temperature, topP: 0.9, maxOutputTokens }
    })
  });
  if (!r.ok) {
    const err = await r.json().catch(() => ({}));
    throw new Error(err?.error?.message || 'Gemini error');
  }
  const payload = await r.json();
  return payload?.candidates?.[0]?.content?.parts?.[0]?.text || '';
}

async function openRouter(system, user) {
  const r = await fetch(OR_URL, {
    method:  'POST',
    headers: {
      'Content-Type':  'application/json',
      'Authorization': `Bearer ${process.env.OPENROUTER_API_KEY}`,
      'HTTP-Referer':  'https://placementsguidegim.vercel.app',
      'X-Title':       'GIM Placement Hub'
    },
    body: JSON.stringify({
      model:    OR_MODEL,
      messages: [{ role: 'system', content: system }, { role: 'user', content: user }],
      temperature: 0.7,
      max_tokens:  2048
    })
  });
  if (!r.ok) {
    const err = await r.json().catch(() => ({}));
    throw new Error(err?.error?.message || `OpenRouter error (${r.status})`);
  }
  const payload = await r.json();
  return payload?.choices?.[0]?.message?.content || '';
}

/* ════════════════════════════════════════════════════════════════════
   UTILS
════════════════════════════════════════════════════════════════════ */

async function withFallback(fns) {
  let lastErr;
  for (const fn of fns) {
    try { return await fn(); } catch (e) { lastErr = e; }
  }
  throw lastErr || new Error('All AI providers failed. Please try again.');
}

function extractJson(raw) {
  const cleaned = raw
    .replace(/<thinking>[\s\S]*?<\/antml:thinking>/gi, '')
    .replace(/```json\s*/gi, '')
    .replace(/```\s*/g, '')
    .trim();
  try { return JSON.parse(cleaned); } catch {}
  const m = cleaned.match(/\{[\s\S]*\}/);
  if (m) { try { return JSON.parse(m[0]); } catch {} }
  return null;
}
