import { requireUser } from '../shared/auth.js';
import { applyCors, methodNotAllowed, sendJson } from '../shared/http.js';
import { checkRateLimit } from '../shared/rateLimit.js';

const MAX_CHECK    = 8000;
const MAX_REPHRASE = 6000;

const GEMINI_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent';
const GROQ_URL   = 'https://api.groq.com/openai/v1/chat/completions';
const GROQ_MODEL = 'llama-3.3-70b-versatile';

const MODE_PROMPTS = {
  professional: 'Rephrase the following text in a clear, professional, and business-appropriate tone. Keep it concise and impactful.',
  academic:     'Rephrase the following text in a formal academic tone suitable for research papers or reports. Use precise language and structured sentences.',
  simplified:   'Rephrase the following text in simple, easy-to-understand language. Use short sentences and avoid jargon so anyone can understand it.',
  creative:     'Rephrase the following text in an engaging, creative, and vivid tone. Make it expressive and memorable while preserving the core meaning.',
  formal:       'Rephrase the following text in a formal, polite, and respectful tone suitable for official communications and letters.'
};

export default async function handler(req, res) {
  if (applyCors(req, res)) return;
  if (req.method !== 'POST') return methodNotAllowed(res, ['POST']);

  const auth = await requireUser(req);
  if (!auth.ok) return sendJson(res, auth.status, { ok: false, error: auth.error });

  const body   = req.body || {};
  const action = String(body.action || '');
  const text   = String(body.text  || '').trim();

  if (!text) return sendJson(res, 400, { ok: false, error: { message: 'Text is required.' } });

  /* ── AI CHECKER (Gemini) ─────────────────────────────────────── */
  if (action === 'ai-check') {
    if (!process.env.GEMINI_API_KEY) {
      return sendJson(res, 503, { ok: false, error: { message: 'AI Checker service not configured.' } });
    }
    const rate = checkRateLimit(`ai-check:${auth.user.id}`, { limit: 10, windowMs: 60_000 });
    if (!rate.allowed) return sendJson(res, 429, { ok: false, error: { message: 'Too many requests. Try again shortly.' } });
    if (text.length > MAX_CHECK) return sendJson(res, 400, { ok: false, error: { message: `Text must be under ${MAX_CHECK} characters.` } });

    const prompt = `You are an expert AI content detector. Analyze the text below and determine how likely it was generated by an AI system (GPT, Gemini, Claude, etc.) vs written by a human.

Return ONLY a valid JSON object with this exact structure (no markdown fences, no extra text, no preamble):
{"probability":<integer 0-100>,"verdict":"<Almost Certainly Human|Likely Human|Uncertain|Likely AI|Almost Certainly AI>","confidence":"<Low|Medium|High>","indicators":["<point1>","<point2>","<point3>"],"explanation":"<2-3 sentence explanation>"}

TEXT TO ANALYZE:
"""
${text}
"""`;

    try {
      const raw    = await gemini(prompt, { temperature: 0.1, maxOutputTokens: 1024 });
      const parsed = extractJson(raw);
      if (!parsed) throw new Error('AI returned an unparseable response. Please try again.');
      return sendJson(res, 200, { ok: true, result: parsed });
    } catch (e) {
      return sendJson(res, 500, { ok: false, error: { message: e.message || 'AI check failed.' } });
    }
  }

  /* ── REPHRASER (Groq — Llama 3.3 70B) ───────────────────────── */
  if (action === 'rephrase') {
    if (!process.env.GROQ_API_KEY) {
      return sendJson(res, 503, { ok: false, error: { message: 'Rephraser service not configured.' } });
    }
    const rate = checkRateLimit(`rephrase:${auth.user.id}`, { limit: 20, windowMs: 60_000 });
    if (!rate.allowed) return sendJson(res, 429, { ok: false, error: { message: 'Too many requests. Try again shortly.' } });
    if (text.length > MAX_REPHRASE) return sendJson(res, 400, { ok: false, error: { message: `Text must be under ${MAX_REPHRASE} characters.` } });

    const mode        = String(body.mode || 'professional').toLowerCase();
    const instruction = MODE_PROMPTS[mode] || MODE_PROMPTS.professional;

    try {
      const rephrased = (await groq(instruction, text)).trim();
      if (!rephrased) throw new Error('AI returned an empty response. Please try again.');
      return sendJson(res, 200, { ok: true, rephrased, mode });
    } catch (e) {
      return sendJson(res, 500, { ok: false, error: { message: e.message || 'Rephrase failed.' } });
    }
  }

  return sendJson(res, 400, { ok: false, error: { message: 'Unknown action. Use "ai-check" or "rephrase".' } });
}

/* ── Groq (OpenAI-compatible) ────────────────────────────────────── */
async function groq(systemPrompt, userText) {
  const r = await fetch(GROQ_URL, {
    method: 'POST',
    headers: {
      'Content-Type':  'application/json',
      'Authorization': `Bearer ${process.env.GROQ_API_KEY}`
    },
    body: JSON.stringify({
      model: GROQ_MODEL,
      messages: [
        { role: 'system', content: systemPrompt + '\n\nReturn ONLY the rephrased text. No explanation, no prefix, no suffix.' },
        { role: 'user',   content: userText }
      ],
      temperature:  0.7,
      max_tokens:   2048,
      top_p:        0.9
    })
  });
  if (!r.ok) {
    const err = await r.json().catch(() => ({}));
    throw new Error(err?.error?.message || `Groq error (${r.status})`);
  }
  const payload = await r.json();
  return payload?.choices?.[0]?.message?.content || '';
}

/* ── Gemini ──────────────────────────────────────────────────────── */
async function gemini(prompt, { temperature = 0.2, maxOutputTokens = 1024 } = {}) {
  const r = await fetch(`${GEMINI_URL}?key=${process.env.GEMINI_API_KEY}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      generationConfig: { temperature, topP: 0.9, maxOutputTokens }
    })
  });
  if (!r.ok) {
    const err = await r.json().catch(() => ({}));
    throw new Error(err?.error?.message || 'Gemini request failed.');
  }
  const payload = await r.json();
  return payload?.candidates?.[0]?.content?.parts?.[0]?.text || '';
}

/* ── Robust JSON extractor (handles Gemini thinking blocks) ─────── */
function extractJson(raw) {
  const cleaned = raw
    .replace(/<thinking>[\s\S]*?<\/antml:thinking>/gi, '')
    .replace(/```json\s*/gi, '')
    .replace(/```\s*/g, '')
    .trim();
  try { return JSON.parse(cleaned); } catch {}
  const m = cleaned.match(/\{[\s\S]*\}/);
  if (m) { try { return JSON.parse(m[0]); } catch {} }
  return null;
}
